### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by geraldstanje** [manki/flickgo#2]
hi, when i run go test i get the following output. any idea?
go test
--- FAIL: TestSignedURL (0.00s)
	flickr_test.go:37: [urlScheme] expcted: <http>, found <https>
	flickr_test.go:37: [urlHost] expcted: <www.flickr.com>, found <api.flickr.com>
FAIL
exit status 1
FAIL	_/Users/gerald/Work/flickgo	0.009s

**Comment by geraldstanje** [comment]
can you verify the line 79 in flickr_test.go needs to be changed:
old:
expected, _ := url.Parse("http://www.flickr.com/services/srv/?" + qry.Encode())
proposed change: 
expected, _ := url.Parse("https://api.flickr.com/services/srv/?" + qry.Encode())

**Comment by manki** [comment]
I just pushed an update. Can you please check again?

**Comment by manki** [comment]
I presume this is resolved now. Let me know if I am mistaken.
